name: test
run-name: run by @${{ github.actor }}
on: 
    workflow_dispatch:
jobs:
    run_python:
        runs-on: ubuntu-latest
        name: Run Python
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                    ptyhon-version: '3.9'
                    architecture: 'x64'
            - name: pip install 
              run: pip install eventlet==0.30.2
            - name: run python
              run: python src/main.py
